const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "",eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0d3K2wvMlNDYjMxUkZyVER2bDdEb2JBbzBQOC9VVWROK0UwelhzMzJGOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZXA5cHR5ZkR0aW1PRnRsWlRuU0cvTk1BZGRCbU8zVkdEVUtMeVVYWkFHbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBRmlXU2c0d0FEVzZoRDNsSnVZOS8veTA1YW4wNnVuWnYwOGZzR21BZWxRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJheUhiNTZSb1E0NW05OWZENjZFOVZCSkxqSk1jcmg3VU9kMmlyZFllWnhJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9IQWRGL1FQV25FeW5FRitMM0EycnZpa3ZqeEw0VmxqWHovQStIdVpNa289In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldQbnlyVkFIRm5veEo3eXU2a3N2a2lqdXdiRWJyK0lNeDZ0R2NkdWZaMXc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUVQSkRTdG44T1hpMUx5TEtxVjhaek5EOWhxUHlJYVV4U0pBeGRoenNGVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUzE3R0VmaXJISGtvZ0x1WEo5L0h3NUl6dTJlUDdldUlOT3NTOGc5eGhEMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZkd2F4S3Q5enRrMElKTmt4VzdRRkdKT1FWRU5DS2w0aXZYOUZvOFc1RlpiM2VzbEg5ZmVucW5NSzhjOEdUUkppS1hDd1QrOGkzbGlOZjg4MDF5eUJ3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTYzLCJhZHZTZWNyZXRLZXkiOiJ2Tm5XTGNWelRxTUJEVkxxRkhjT05SWVdLVlhhWXdLR1B2T1dySCt5QmVzPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJkd253cjVrcFRxNlg0T3J6SlFXdW5BIiwicGhvbmVJZCI6IjdhZjhmNWQ2LTI2MjMtNDU4My05YmVjLWMyYTFlMjRjYTI4NCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLS1NuWE9na1pTTEU1UXlEQU1ZSDA4NGh3cEk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWmo1RDBhNWlnQ09vOWh3Q2N3dndPeEtTVUhnPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkZRWkVQSkZOIiwibWUiOnsiaWQiOiIyMzQ5MDI5MjYyNzE3OjE4QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkRlc2JveTAwMiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUEhrd0k4RUVPNms3THNHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiMnRyN085QTFWZHlhMHNCQzRXVGlzekhHVE1wK1J1QVR2RnlHdS9Sbld5Zz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiU1J1aWQyQ0JuN2RORm1hTGRBbTdlbmpFRkNPS2dxemVxOGZLeU9RT0FqTlordXVLVEpJZVFjckFmUWE1NlpzcFZmdTl0Y2x5bDRGRnMwbkFNSGw2Qnc9PSIsImRldmljZVNpZ25hdHVyZSI6InhhNHNaeDZ6QStEK3dHWVFrRU1qV0pvdWNrVUlEbUZ2VUlGaWZpbHJTSllTdFFKcGxoZm93UzVOdHJBanFQUWhxWUNVRVdhNlRlZ2Z5VUNBZUc3UUJBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0OTAyOTI2MjcxNzoxOEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJkcmErenZRTlZYY210TEFRdUZrNHJNeHhrektma2JnRTd4Y2hydjBaMXNvIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM2MTE4OTA3fQ==
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
